// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/inference.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceWorker_Predict_FullMethodName     = "/inference.InferenceWorker/Predict"
	InferenceWorker_CheckHealth_FullMethodName = "/inference.InferenceWorker/CheckHealth"
)

// InferenceWorkerClient is the client API for InferenceWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InferenceWorker is the gRPC service exposed by each ML backend worker node.
type InferenceWorkerClient interface {
	// Predict runs inference on a batch of requests.
	Predict(ctx context.Context, in *BatchInferenceRequest, opts ...grpc.CallOption) (*BatchInferenceResponse, error)
	// CheckHealth returns the health status of the worker.
	CheckHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type inferenceWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceWorkerClient(cc grpc.ClientConnInterface) InferenceWorkerClient {
	return &inferenceWorkerClient{cc}
}

func (c *inferenceWorkerClient) Predict(ctx context.Context, in *BatchInferenceRequest, opts ...grpc.CallOption) (*BatchInferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInferenceResponse)
	err := c.cc.Invoke(ctx, InferenceWorker_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceWorkerClient) CheckHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, InferenceWorker_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceWorkerServer is the server API for InferenceWorker service.
// All implementations must embed UnimplementedInferenceWorkerServer
// for forward compatibility.
//
// InferenceWorker is the gRPC service exposed by each ML backend worker node.
type InferenceWorkerServer interface {
	// Predict runs inference on a batch of requests.
	Predict(context.Context, *BatchInferenceRequest) (*BatchInferenceResponse, error)
	// CheckHealth returns the health status of the worker.
	CheckHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedInferenceWorkerServer()
}

// UnimplementedInferenceWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceWorkerServer struct{}

func (UnimplementedInferenceWorkerServer) Predict(context.Context, *BatchInferenceRequest) (*BatchInferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedInferenceWorkerServer) CheckHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedInferenceWorkerServer) mustEmbedUnimplementedInferenceWorkerServer() {}
func (UnimplementedInferenceWorkerServer) testEmbeddedByValue()                         {}

// UnsafeInferenceWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceWorkerServer will
// result in compilation errors.
type UnsafeInferenceWorkerServer interface {
	mustEmbedUnimplementedInferenceWorkerServer()
}

func RegisterInferenceWorkerServer(s grpc.ServiceRegistrar, srv InferenceWorkerServer) {
	// If the following call pancis, it indicates UnimplementedInferenceWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceWorker_ServiceDesc, srv)
}

func _InferenceWorker_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceWorkerServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceWorker_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceWorkerServer).Predict(ctx, req.(*BatchInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceWorker_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceWorkerServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceWorker_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceWorkerServer).CheckHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceWorker_ServiceDesc is the grpc.ServiceDesc for InferenceWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.InferenceWorker",
	HandlerType: (*InferenceWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _InferenceWorker_Predict_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _InferenceWorker_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/inference.proto",
}
